### ISSUE TITLE
Add a utility to remove the shadow on hover from the card

### ISSUE THREAD

**Issue by ErikThiart** [outboxcraft/beauter#21]
Any way to add a utility class to prevent the shadow on hover for cards? 

I just want a normal card, no hover effect.

**Comment by ramdeoshubham** [comment]
Hello Erik!
Thanks for always suggesting nice ideas to increase beauter's adaptibility.

I am assuming that you want the cards to stop reacting on hover. The safest way would be to override the hover effect with the default. I believe something like shall help. Add this at the end of the `head` section.

```html
<style>
.card:hover {-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, .2);box-shadow: 0 4px 8px 0 rgba(0, 0, 0, .2);}
</style>
```

Please let me know if it doesn't help.

**Comment by ramdeoshubham** [comment]
In case you want a seperate utility, you can extend the above idea with a class:

```css
.card-nohover:hover {-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, .2);box-shadow: 0 4px 8px 0 rgba(0, 0, 0, .2);}
```

Now with your cards, you can do something like:

```html
<div class="card card-nohover" ... >
    ...
</div>
```

I hope I am able to help you.
